# 빌드 이미지
FROM gradle:8.8-jdk17 as build

WORKDIR /app

# Gradle 빌드 (JAR 파일 생성)
COPY . .
RUN gradle clean build -x test --no-daemon

# Base image
FROM openjdk:17-jdk-slim

# 작업 디렉터리 설정
WORKDIR /usr/local/app

# JAR 파일 복사 (빌드 이미지에서 생성된 JAR 파일을 복사)
COPY --from=build /app/build/libs/co-working-0.0.1-SNAPSHOT.jar /usr/local/app/co-working-0.0.1-SNAPSHOT.jar

# 애플리케이션 실행
ENTRYPOINT ["java", "-jar", "/usr/local/app/co-working-0.0.1-SNAPSHOT.jar"]

# 기본 포트 설정
EXPOSE 18080